package org.francis.kcb_assessment.config.doc;

public class SwaggerDocSamples {
    public static final String CREATE_PROJECT_REQUEST = "{\"name\":\"My Project AA description\",\"description\":\"ProjectAA\"}";
    public static final String CREATE_PROJECT_RESPONSE = "{\"id\":1,\"name\":\"My Project AA description\",\"description\":\"ProjectAA\"}";
    public static final String GET_PROJECTS_RESPONSE = "{\"content\":[{\"id\":1,\"name\":\"Project ABC\",\"description\":\"My Description\"},{\"id\":2,\"name\":\"Project Monday\",\"description\":\"My Project Monday description\"},{\"id\":3,\"name\":\"Epic Project\",\"description\":\"Epic Description\"}],\"pageable\":{\"pageNumber\":0,\"pageSize\":20,\"sort\":{\"empty\":true,\"sorted\":false,\"unsorted\":true},\"offset\":0,\"paged\":true,\"unpaged\":false},\"last\":true,\"totalPages\":1,\"totalElements\":3,\"first\":true,\"size\":20,\"number\":0,\"sort\":{\"empty\":true,\"sorted\":false,\"unsorted\":true},\"numberOfElements\":3,\"empty\":false}";
    public static final String GET_PROJECT_RESPONSE = "{\"id\":2,\"name\":\"Project Monday\",\"description\":\"My Project Monday description\"}";
    public static final String CREATE_TASK_RESPONSE = "{\"id\":1,\"title\":\"Juma Printing Task\",\"description\":\"Printing docs task\",\"status\":\"TO_DO\",\"dueDate\":\"2024-12-05\"}";
    public static final String CREATE_TASK_REQUEST = "{\"title\":\"Juma Printing Task\",\"description\":\"Printing docs task\",\"dueDate\":\"2024-12-05\"}";
    public static final String GET_TASKS_RESPONSE = "{\"content\":[{\"id\":1,\"title\":\"Online backup\",\"description\":\"Frank Task\",\"status\":\"DONE\",\"dueDate\":\"2024-12-02\"},{\"id\":2,\"title\":\"Filing Task\",\"description\":\"Ken filing Task\",\"status\":\"IN_PROGRESS\",\"dueDate\":\"2024-12-10\"},{\"id\":3,\"title\":\"Send By Posta Task\",\"description\":\"Jane Task\",\"status\":\"TO_DO\",\"dueDate\":\"2024-12-11\"},{\"id\":4,\"title\":\"Create Duplicate Task\",\"description\":\"Jane Task\",\"status\":\"TO_DO\",\"dueDate\":\"2024-12-11\"}],\"pageable\":{\"pageNumber\":0,\"pageSize\":20,\"sort\":{\"empty\":true,\"unsorted\":true,\"sorted\":false},\"offset\":0,\"unpaged\":false,\"paged\":true},\"last\":true,\"totalElements\":4,\"totalPages\":1,\"size\":20,\"number\":0,\"sort\":{\"empty\":true,\"unsorted\":true,\"sorted\":false},\"first\":true,\"numberOfElements\":4,\"empty\":false}";
    public static final String GET_TASK_RESPONSE = "{\"id\":1,\"title\":\"Online backup\",\"description\":\"Frank Task\",\"status\":\"DONE\",\"dueDate\":\"2024-12-02\"}";
    public static final String UPDATE_TASK_RESPONSE = "{\"id\":2,\"title\":\"Filing Task\",\"description\":\"Ken filing Task\",\"status\":\"DONE\",\"dueDate\":\"2024-12-05\"}";
    public static final String UPDATE_TASK_REQUEST = "{\"title\":\"Filing Task\",\"description\":\"Ken filing Task\",\"status\":\"DONE\",\"dueDate\":\"2024-12-05\"}";
    public static final String GET_PROJECT_SUMMARY_RESPONSE = "{\"content\":[{\"id\":1,\"name\":null,\"description\":\"My Description\",\"taskSummary\":[]},{\"id\":2,\"name\":null,\"description\":\"My Project Monday description\",\"taskSummary\":[]},{\"id\":3,\"name\":null,\"description\":\"Epic Description\",\"taskSummary\":[{\"taskStatus\":\"DONE\",\"count\":1},{\"taskStatus\":\"IN_PROGRESS\",\"count\":1},{\"taskStatus\":\"TO_DO\",\"count\":2}]}],\"pageable\":{\"pageNumber\":0,\"pageSize\":20,\"sort\":{\"sorted\":false,\"empty\":true,\"unsorted\":true},\"offset\":0,\"paged\":true,\"unpaged\":false},\"last\":true,\"totalPages\":1,\"totalElements\":3,\"first\":true,\"size\":20,\"number\":0,\"sort\":{\"sorted\":false,\"empty\":true,\"unsorted\":true},\"numberOfElements\":3,\"empty\":false}";
}
